{%set name = "jsonpatch" %}
{%set version = "1.15" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "ae23cd08b2f7246f8f2475363501e740c4ef93f08f2a3b7b9bcfac0cc37fceb1" %}
{%set build_num = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - jsonpointer >=1.9

test:
  imports:
    - jsonpatch

about:
  home: https://github.com/stefankoegl/python-json-patch
  license: BSD 3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'Apply JSON-Patches (RFC 6902)'
  dev_url: https://github.com/stefankoegl/python-json-patch
  doc_url: https://python-json-patch.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
