# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hIDT7ktB+fMRCy0lATGYfRgt2xWTE6DkqwiGTHN7BXJacgh+RkWPCbAKAYBo9iyHvCH40GcWzfK7dqNPa325Y3ew/Nf9Ojf+h4am7OoJIcMnQV8SyjP9iOjh6OUbKTJyt5p9zkIGlMRAqvXOQwIj+EOwOOZWBhm5vFQ0Tb5g9zTAk3fUosQJeq7iISTDijs+xY5mATXScnArJQYrLa66nUVXCRQ9Eu1uNuvSxMM4sdtaU/WrlWLuwTEClWFrgiZmB19pR/Lf+0gyDTbh67hFcIlDQr/9GO2ke+07CEYyNXSDQjWp24py+DK85LS08IK90nPs3K6UxMu0nU7E41jWaO0EiEtBhX+tzmmMqMXmS2NoTZON5jzx5GIjUGdkTKAmxKK7TXEVuZnlftHEC5J9SIS2Yno3LhwtFPJWI+2YQPt1O1/rv6QI8ntmm5BE9+MdrlItUVIrFkHz8WQytq0J3GjeIwGKZEF0ycjiXfuVekThg2E9jBR5O/y6RN2LjbXIFcxS0dcfXY+plpnokkrLez67vbMvxY+7gu+MYa9BZ6sk13EM9zyRd+6BDeBJuxzPCKYY9OJE+BFg9uSr+BMQZM9/P575nXE9N2Kgvg/B/4JnLZmt7gU2qTgw7eiQy5J+Dk5qni4MTkOk8cSfH0jhFLr9GnMcCpnjC0xLNhPPBpo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
