travis:
  secure:
    BINSTAR_TOKEN: OkN4zK6iyzU/td39Ceo+eXK3AdoJY9vZl/a/iLI5XlqVLZNIU2VUi4vMY6id8j2sF9ScqRPbE/yQtBg0334wfn0HiPXmVHOVekOL2eOmD4aTTkHuOltfYCuuH9IIJw2JXhhnsjDqv/4g7T6U4czdffGRqCW/umDOE3MAIV3d42v4K7n8DP3yJyKXaUZBPeQwRnM1nEx6JIi86ouzVDiwIbls+k/ArFRczB/Uq9mJ9gpvfH22vbxwzyCnix4Nk0LFy9Dl5XXg90JA8zb4Jw+KrF+isnPo7i9dhT/BPmBO6ZU3anW6AXs5q22x8wre0vJBR2oBAxRsc+Q3xWbgZRb3fBQ0Hoc34d93zQVz7RIAyULm5f00TMY2Y7iwEJ8HgNhIYEg9yw0XQLmOyulBCUKPqywfB1jY0wUkTOoC8LLwYG1gbrv1QxE7KOWF+rwWtwbCxgikdpPOUQ34tkKCoTgyVvFHQBTUHajMXHtyZm9KGJ2SDDQnBAOlJvXd4hHyGd7oyq/LVaxCJkKMHTVatwDEG9fD8THjTQ3Trj+8RooKudUVOKUdmlVuCOJVnl0Y3232f8Fn0h3mUS7wkrKCXtVk76axAuhtz0GHzhHR5uL1OrJy1t3AT93qEOt9RGUVkamMBEwbUExPsxVgzXQ2kUhAPJJNg6wmvxYlDGa4CzzPQlA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
