travis:
  secure:
    BINSTAR_TOKEN: u7GTZOZeKcR/4Q+Ko20WM8ke0Sf8E5hPHbW6UQQ/2st/e2moc7EQWRJsxeJELl+lNlXz0w5Tw+HZlof2B9/o7/40pCgDGbboYfAO4KoZJSp+FyvuqkhzQiZnHB+v2W1ljak+oP84xBQap7o1GlWXE1OjBaC8bOL9mt3Ky7kjrQMaLrI0anAoC/xkBAAt1tyzHEFnlo0igW+ihG9QZ6wUuhzLGlZxmf6caQxfVHh3bzGbRiEZRB9jEHh2hwKeFK5TGkTuriCSQxUy5WANkntmiY0kK4fm1tOoHORbHrv8jDhSuuOy7F4241djFao5fJYIflg9B49lm2GFzntdLLUXbn3MlRrkGLoEtp9XSHnjhtN8ImDQWRlU77fgOpWnWs5tAIGFpQpZKCmr+cv8kOHP+ZZcp7uiRbsaKBV7pFbTCbjVZwqhYmCNtFtcxpBxIbpFcNI7TLH80cD3ONy+ZrBdPBgd2m5c0MOz4jOzMAOiMUDt8KJQU3dBfnx2a5+Xc3rIqBlDkAWTSqJp04rfacibeDGkQBLcWSstoKtgi9yCke6P6WsDnoj2J6bVN+4QgPE62uc44IP8f9vZWBzadkCdPxlDJ7k9om1Yi5SXVbTlIPZlgHaR66S1E4oJysI51xOXPO0gHyJ85z5eFRfYH12hgS2xx5FH5/9/J8ErzMiofZw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
