travis:
  secure:
    BINSTAR_TOKEN: hIDT7ktB+fMRCy0lATGYfRgt2xWTE6DkqwiGTHN7BXJacgh+RkWPCbAKAYBo9iyHvCH40GcWzfK7dqNPa325Y3ew/Nf9Ojf+h4am7OoJIcMnQV8SyjP9iOjh6OUbKTJyt5p9zkIGlMRAqvXOQwIj+EOwOOZWBhm5vFQ0Tb5g9zTAk3fUosQJeq7iISTDijs+xY5mATXScnArJQYrLa66nUVXCRQ9Eu1uNuvSxMM4sdtaU/WrlWLuwTEClWFrgiZmB19pR/Lf+0gyDTbh67hFcIlDQr/9GO2ke+07CEYyNXSDQjWp24py+DK85LS08IK90nPs3K6UxMu0nU7E41jWaO0EiEtBhX+tzmmMqMXmS2NoTZON5jzx5GIjUGdkTKAmxKK7TXEVuZnlftHEC5J9SIS2Yno3LhwtFPJWI+2YQPt1O1/rv6QI8ntmm5BE9+MdrlItUVIrFkHz8WQytq0J3GjeIwGKZEF0ycjiXfuVekThg2E9jBR5O/y6RN2LjbXIFcxS0dcfXY+plpnokkrLez67vbMvxY+7gu+MYa9BZ6sk13EM9zyRd+6BDeBJuxzPCKYY9OJE+BFg9uSr+BMQZM9/P575nXE9N2Kgvg/B/4JnLZmt7gU2qTgw7eiQy5J+Dk5qni4MTkOk8cSfH0jhFLr9GnMcCpnjC0xLNhPPBpo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
